name: CI

on: [push]

jobs:

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ppa-version:
          # this is currently neovim 0.6.1 and does not work/takes forever
          #- stable
          - unstable
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        sudo add-apt-repository -y ppa:neovim-ppa/${{ matrix.ppa-version }}
        sudo apt-get update
        sudo apt-get install -yqq --no-install-recommends neovim scdoc lua-busted
    - name: Show neovim version
      run: nvim --version
    - name: Run the test suite
      run: script -ec "make test"
      env:
        TERM: dumb

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        brew update
        brew install neovim scdoc luarocks
        luarocks --local install busted
    - name: Show neovim version
      run: nvim --version
    - name: Run the test suite
      run: script typescript make test BUSTED="$HOME/.luarocks/bin/busted --exclude-tags=osx_pending"
      env:
        TERM: dumb

  nix:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v16
    - uses: actions/checkout@v2
    - name: Run the test suite
      run: script -ec 'nix develop --command sh -c "nvim --version; make test"'
      env:
        TERM: dumb

  nix-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          #- "070"  # broken?
          - "071"
          - "072"
          - dev
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v16
    - uses: actions/checkout@v2
    - name: Run the test suite
      run: script -ec 'nix develop .\#with-neovim-versions --command sh -c "$NVIMPAGER_NVIM --version; make test"'
      env:
        TERM: dumb
        NVIMPAGER_NVIM: neovim-${{ matrix.version }}
